routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\ProduitController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BasketController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('accueil');
Route::get('/categories/recherche', [CategorieController::class, 'recherche'])->name('categories.recherche');

Route::get('/', [ProduitController::class, 'indexp'])->name('welcome');

Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);
Route::prefix('basket')->group(function () {
    Route::get('/', [BasketController::class, 'index'])->name('basket.index');
    Route::post('/remove/{product}', [BasketController::class, 'removeFromBasket'])->name('basket.remove');});
    Route::post('/add-to-basket/{product}', [BasketController::class, 'addToBasket'])->name('basket.add');
    Route::get('/basket/destroy', [BasketController::class, 'destroyBasket'])->name('basket.destroy');
    Route::get('/basket/commander',[BasketController::class,"commander"])->name('basket.commander');

        

resources/views/categories/create.blade.php
 @extends('layouts.admin')
 @section('title','Ajouter une categorie')
 @section('content')
    <h1>Creer une nouvelle categorie</h1>
    <form action="{{route('categories.store')}}" method="POST">
        @csrf
        <div>
        <label for="designation">Designation</label>
        <input type="text" name="designation" id="designation" value="{{old('designation')}}">
        </div>
         <div>
        <label for="description">Description</label>
       <textarea name="description" id="description" cols="30" rows="10" >{{old('designation')}}</textarea>
          
        </div>
        <div>
            <input type="submit" value="Ajouter">
        </div>
    </form>
    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>
           
           @endforeach
        </ul>
         


        @endif
    </div>
@endsection

resources/views/categories/edit.blade.php
 @extends('layouts.admin')
 @section('title','Modifier une categorie')
 @section('content')
    <h1>Modifier la categorie num {{$cat->id}}</h1>
    <form action="{{route('categories.update',['category'=>$cat->id])}}" method="POST">
        @csrf
        @method('PUT')
        <div>
        <label for="designation">Designation</label>
        <input type="text" name="designation" id="designation" value="{{old('designation',$cat->designation)}}">
        </div>
         <div>
        <label for="description">Description</label>
       <textarea name="description" id="description" cols="30" rows="10" >{{old('designation',$cat->description)}}</textarea>
          
        </div>
        <div>
            <input type="submit" value="Modifier">
        </div>
    </form>
    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>
           
           @endforeach
        </ul>
         


        @endif
    </div>

@endsection

resources/views/categories/index.blade.php
 @extends('layouts.admin')
 @section('title','Gestion des categories')
 @section('content')
     
    <h1>Liste des categories</h1>
    <a href="{{route('categories.create')}}">Ajouter une nouvelle categorie</a>
    <a href="{{route('categories.recherche')}}">Rechercher de categorie</a>
    <table id="tbl">
      <tr>
          <th>Id</th>
        <th>Designation</th>
        <th>Description</th>
        <th colspan="3">Actions</th>
      </tr>
      @foreach ($categories as $cat)
          <tr>
            <td>{{$cat->id}}</td>
            <td>{{$cat->designation}}</td>
            <td>{{$cat->description}}</td>
            <td><a href="{{route('categories.show',['category'=>$cat->id])}}">Details</a></td>
            <td><a href="{{route('categories.edit',['category'=>$cat->id])}}">Modifier</a></td>
            <td>
                <form action="{{route('categories.destroy',['category'=>$cat->id])}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <input type="submit" value="Supprimer" onclick="return confirm('voulez-vous supprimer cette categorie?')">
                </form></td>
          </tr>
      @endforeach
    </table>
    <a href="{{route('categories.recherche')}}">Rechercher de categorie</a>
 @endsection

resources/views/categories/recherche.blade.php
<!-- resources/views/categories/recherche.blade.php -->

@extends('layouts.admin') <!-- Make sure to adjust the layout as per your application -->

@section('title', 'Recherche de catégorie')

@section('content')

    <h1>Recherche de catégorie</h1>

    <form action="{{ route('categories.recherche') }}" method="GET">
        @csrf

        <label for="designation">Designation:</label>
        <input type="text" name="designation" id="designation" required>

        <button type="submit">Rechercher</button>
    </form>

    @if(isset($cat))
        <div>
            <h2>Résultat de la recherche</h2>
            <p>ID: {{ $cat->id }}</p>
            <p>Designation: {{ $cat->designation }}</p>
            <p>Description: {{ $cat->description }}</p>
        </div>
        
    @else
    <div> designation non trouver</div>
        
    @endif
    

@endsection

resources/views/categories/show.blade.php
 @extends('layouts.admin')
 @section('title','Detail d \'une categorie')
 @section('content')
    <a href="{{route('categories.index')}}">Retourner vers la liste des categories</a>
    <h1>Detail de la categorie Num {{$cat->id}}</h1>
    <div>
        <p><strong>Designation:</strong> {{$cat->designation}}</p>
        <p><strong>Description:</strong> {{$cat->description}}</p>
    </div>
@endsection