routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\ProduitController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BasketController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('accueil');
Route::get('/categories/recherche', [CategorieController::class, 'recherche'])->name('categories.recherche');

Route::get('/', [ProduitController::class, 'indexp'])->name('welcome');

Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);
Route::prefix('basket')->group(function () {
    Route::get('/', [BasketController::class, 'index'])->name('basket.index');
    Route::post('/remove/{product}', [BasketController::class, 'removeFromBasket'])->name('basket.remove');});
    Route::post('/add-to-basket/{product}', [BasketController::class, 'addToBasket'])->name('basket.add');
    Route::get('/basket/destroy', [BasketController::class, 'destroyBasket'])->name('basket.destroy');
    Route::get('/basket/commander',[BasketController::class,"commander"])->name('basket.commander');

        

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('css/main.css')}}">
    <title>@yield('title','App store')</title>
</head>
<body>
    <nav>
        <ul>
             <li><a href="{{route('welcome')}}">Accueil</a></li> 
            <li><a href="{{route('categories.index')}}">Gestion des categories</a></li>
            <li><a href="{{route('produits.index')}}">Gestion des produits</a></li>
            <li><a href="{{route('basket.index')}}">Mon panier</a></li>

        </ul>
    </nav>
    <div class="main">
        @yield('content')
    </div>
    <footer>
        &copy;OFPPT 2024
    </footer>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title')</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body>
    <div class="container">
        @yield('content')
    </div>

    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>