routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\ProduitController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BasketController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('accueil');
Route::get('/categories/recherche', [CategorieController::class, 'recherche'])->name('categories.recherche');

Route::get('/', [ProduitController::class, 'indexp'])->name('welcome');

Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);
Route::prefix('basket')->group(function () {
    Route::get('/', [BasketController::class, 'index'])->name('basket.index');
    Route::post('/remove/{product}', [BasketController::class, 'removeFromBasket'])->name('basket.remove');});
    Route::post('/add-to-basket/{product}', [BasketController::class, 'addToBasket'])->name('basket.add');
    Route::get('/basket/destroy', [BasketController::class, 'destroyBasket'])->name('basket.destroy');
    Route::get('/basket/commander',[BasketController::class,"commander"])->name('basket.commander');

        

app/Models/Produit.php
<?php

namespace App\Models;

use App\Models\Categorie;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Produit extends Model
{
    use HasFactory;
    protected $fillable =[
        'designation',
        'prix_u',
        'quantite_stock',
        'categorie_id',
        'photo',
    ];
    public function categorie(){
       return  $this->belongsTo(Categorie::class);
    }
}

app/Http/Controllers/ProduitController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produit;
use App\Models\Categorie;
use Illuminate\Http\Request;

class ProduitController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        //$produits=Produit::all();
        //$produits=Produit::paginate(10);
        //$designation = $request->input('designation');
        //$designation = $request->query('designation');
        //$produits = Produit::where('designation', 'like','%' . $designation . '%')->get();
       
        $designation = $request->query('designation');
        $min_prix = $request->query('min_prix');
        $max_prix = $request->query('max_prix');
        $quantite_null = $request->query('quantite_null');
        
        $query = Produit::query();
        if ($designation) {
            $query->where('designation', 'like', '%' . $designation . '%');
        }
    
        if ($min_prix) {
            $query->where('prix_u', '>=', $min_prix);
        }
        if ($max_prix) {
            $query->where('prix_u', '<=', $max_prix);
        }
        if ($quantite_null) {
            $query->where('quantite_stock', '=', 0);
        }
        $nbr_produits = count($query->get());
        $produits = $query->paginate(10);
        
       
         return view("produits.index",compact('produits','designation','min_prix','max_prix','quantite_null','nbr_produits'));
       
       
    
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories=Categorie::all();
        return view('produits.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
        // $request->file('photo')->store('produit','public');
        $data = $request->validate([
            'designation'=>'required|unique:produits,designation',
            'prix_u'=>'required|integer|between:0,99999',
            'quantite_stock'=>'required|integer|between:1,9999',
            'photo'=>'required|image|mimes:png,jpg,svg,jpeg|max:40000',
            'categorie_id'=>'required'
        ]);
        if ($request->hasFile('photo')){
          $data['photo'] = $request->file('photo')->store('produit','public');
            
        }
        $product = Produit::create($data);

    // Associate the product with the user's basket (assuming you have user authentication)
    auth()->user()->basket()->attach($product->id, ['quantity' => 1]);

    
        
       Produit::create($data); 
        return  redirect()->route('produits.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $pro=Produit::find($id);
        
        return view('produits.show')->with("pro",$pro);
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $categories=Categorie::all();
        $pro=Produit::find($id);
        return view('produits.edit',compact('pro','categories'));
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $data =$request->validate([
            'designation'=>'required|unique:produits,designation,'.$id,
            'prix_u'=>'required|integer|between:0,99999',
            'quantite_stock'=>'required|integer|between:0,9999',
            'photo'=>'required|image|mimes:png,jpg,svg,jpeg|max:40000',
            'categorie_id'=>'required'
       ]);
       if ($request->hasFile('photo')){
        $data['photo'] = $request->file('photo')->store('produit','public');
          
      }
        $pro=Produit::find($id);
        //$pro->update($request->all());
        $pro->update($data);
        return redirect()->route('produits.index');
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Produit::destroy($id);
        return  redirect()->route('produits.index');

        //
    }
    public function indexp()
    {
        $produits=Produit::all();
       
        return view("welcome",compact('produits'));
    }
}

resources/views/produits/create.blade.php
@extends('layouts.admin')
 @section('title','Ajouter une produit')
 @section('content')
    <h1>Creer une nouvelle produit</h1>
    <form action="{{route('produits.store')}}" method="POST" enctype="multipart/form-data">
        @csrf
        <div>
        <label for="designation">Designation</label>
        <input type="text" name="designation" id="designation" value="{{old('designation')}}">
        </div>
        <div>
        <label for="prix_u">prix_u</label>
        <input type="text" name="prix_u" id="prix_u" value="{{old('prix_u')}}">
        </div>
        <div>
        <label for="quantite_stock">quantite_stock</label>
        <input type="text" name="quantite_stock" id="quantite_stock" value="{{old('quantite_stock')}}">
        </div>
        <div>
        <label for="categorie_id">Choose a categorie_id:</label>

        <select name="categorie_id" id="categorie_id">
        @foreach ($categories as $cat)
          <option value="{{$cat->id}}">{{$cat->id}}</option>
          @endforeach
        </select>
        </div>
        <div>
            <label for="photo">Photo</label>
            <input type="file" name="photo" id="photo">
        </div>
         
        <div>
            <input type="submit" value="Ajouter">
        </div>
    </form>
    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>
           
           @endforeach
        </ul>
         


        @endif
    </div>
@endsection

resources/views/produits/edit.blade.php
@extends('layouts.admin')
 @section('title','Modifier une produit')
 @section('content')
    <h1>Modifier la produit num {{$pro->id}}</h1>
    <form action="{{route('produits.update',['produit'=>$pro->id])}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div>
        <label for="designation">Designation</label>
        <input type="text" name="designation" id="designation" value="{{old('designation',$pro->designation)}}">
        </div>
        <div>
        <label for="prix_u">prix_u</label>
        <input type="text" name="prix_u" id="prix_u" value="{{old('prix_u',$pro->prix_u)}}">
        </div>
        <div>
        <label for="quantite_stock">quantite_stock</label>
        <input type="text" name="quantite_stock" id="quantite_stock" value="{{old('quantite_stock',$pro->quantite_stock)}}">
        </div>
        <div>
        <label for="categorie_id">Choose a categorie_id:</label>
        <select name="categorie_id" id="categorie_id">
        @foreach ($categories as $cat)
         
          <option value="{{ $cat->id }}" {{ ( $pro->categorie_id == $cat->id) ? 'selected' : '' }}>
                {{ $cat->id }}
            </option>
            
          @endforeach
        </select>
        
        </div>
        <div>
          <label for="photo">Photo</label>
          <input type="file" name="photo" id="photo">
      </div>
         
        <div>
            <input type="submit" value="Ajouter">
        </div>
    </form>
    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>
           
           @endforeach
        </ul>
         


        @endif
    </div>
@endsection

resources/views/produits/index.blade.php
@extends('layouts.admin')
 @section('title','Gestion des produits')
 @section('content')
     
 <h1>Recherche de produit</h1>

 <form action="{{ route('produits.index') }}" method="GET" class="row g-3">
  @csrf

  <div class="col-md-3">
      <label for="designation" class="form-label">Designation:</label>
      <input type="text" name="designation" id="designation" value="{{ old('designation', $designation) }}" class="form-control">
  </div>

  <div class="col-md-3">
      <label for="min_prix" class="form-label">min_prix:</label>
      <input type="text" name="min_prix" id="min_prix" value="{{ old('min_prix', $min_prix) }}" class="form-control">
  </div>

  <div class="col-md-3">
      <label for="max_prix" class="form-label">max_prix:</label>
      <input type="text" name="max_prix" id="max_prix" value="{{ old('max_prix', $max_prix) }}" class="form-control">
  </div>

  <div class="col-md-2 form-check">
      <input type="checkbox" id="quantite_null" name="quantite_null" value="quantite_null" {{ $quantite_null ? 'checked' : '' }} class="form-check-input">
      <label for="quantite_null" class="form-check-label"> produit hors stock</label>
  </div>

  <div class="col-md-1">
      <button type="submit" class="btn btn-primary">Rechercher</button>
  </div>
</form>

    <h1>Liste des produits</h1>
    <span>Resultat : {{$nbr_produits}}</span>
    <a href="{{route('produits.create')}}" class="btn btn-primary">Ajouter une nouvelle produit</a>
    <table id="tbl">
      <tr>
          <th>Id</th>
        <th>Designation</th>
        
        <th>prix_u</th>
        <th>quantite_stock</th>
        <th>categorie_id</th>
        <th colspan="3">Actions</th>
      </tr>
      @foreach ($produits as $pro)
          <tr>
            <td>{{$pro->id}}</td>
            <td>{{$pro->designation}}</td>
            <td>{{$pro->prix_u}}</td>
            <td>{{$pro->quantite_stock}}</td>
            <td>{{$pro->categorie_id}}</td>
            <td><a href="{{route('produits.show',['produit'=>$pro->id])}}" class="btn btn-info">Details</a></td>
            <td><a href="{{route('produits.edit',['produit'=>$pro->id])}}" class="btn btn-warning">Modifier</a></td>
            <td>
                <form action="{{route('produits.destroy',['produit'=>$pro->id])}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <input type="submit" value="Supprimer" onclick="return confirm('voulez-vous supprimer cette produit?')" class="btn btn-danger">
                </form></td>
          </tr>
      @endforeach
    </table>
    {{$produits->links()}}
 @endsection

resources/views/produits/show.blade.php
@extends('layouts.admin')
 @section('title','Detail d \'une produit')
 @section('content')
    <a href="{{route('produits.index')}}" enctype="multipart/form-data">Retourner vers la liste des produits</a>
    <h1>Detail de la produit Num {{$pro->id}}</h1>
    <div>
        <p><strong>Designation:</strong> {{$pro->designation}}</p>
        <p><strong>prix_u:</strong> {{$pro->prix_u}}</p>
        <p><strong>quantite_stock:</strong> {{$pro->quantite_stock}}</p>
        <p><strong>categorie_id:</strong> {{$pro->categorie_id}}</p>
        
    </div>
    @if ($pro->photo)
        <img src="{{ asset('storage/' . $pro->photo) }}" alt="Product Photo" style="max-width: 300px; max-height: 300px;">
    @else
        <p>No photo available</p>
    @endif
@endsection